using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Keepr.Api.Data.Migrations
{
    /// <inheritdoc />
    public partial class AddEmailSettings : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // CREATE TABLE IF NOT EXISTS (raw SQL rather than CreateTable) because Down() intentionally
            // retains this shared key ring — so a rollback-then-reapply must not fail on an existing
            // table. Shape matches the Npgsql-generated DataProtectionKey mapping. See §8.
            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS keepr.""DataProtectionKeys"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
                    ""FriendlyName"" text NULL,
                    ""Xml"" text NULL,
                    CONSTRAINT ""PK_DataProtectionKeys"" PRIMARY KEY (""Id"")
                );");

            migrationBuilder.CreateTable(
                name: "EmailSettings",
                schema: "keepr",
                columns: table => new
                {
                    Id = table.Column<int>(type: "integer", nullable: false),
                    Provider = table.Column<string>(type: "character varying(16)", maxLength: 16, nullable: false, defaultValue: "None"),
                    FromAddress = table.Column<string>(type: "character varying(320)", maxLength: 320, nullable: false),
                    FromName = table.Column<string>(type: "character varying(200)", maxLength: 200, nullable: false),
                    ApiKeyCipher = table.Column<byte[]>(type: "bytea", nullable: true),
                    MailgunDomain = table.Column<string>(type: "character varying(255)", maxLength: 255, nullable: true),
                    MailgunRegion = table.Column<string>(type: "character varying(2)", maxLength: 2, nullable: true),
                    PublicBaseUrl = table.Column<string>(type: "character varying(2048)", maxLength: 2048, nullable: false),
                    InviteExpiryDays = table.Column<int>(type: "integer", nullable: false),
                    LastTestAt = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true),
                    LastTestOk = table.Column<bool>(type: "boolean", nullable: true),
                    LastTestError = table.Column<string>(type: "character varying(2000)", maxLength: 2000, nullable: true),
                    UpdatedAt = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false),
                    UpdatedByUserId = table.Column<Guid>(type: "uuid", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_EmailSettings", x => x.Id);
                    table.CheckConstraint("CK_EmailSettings_Singleton", "\"Id\" = 1");
                });

            migrationBuilder.InsertData(
                schema: "keepr",
                table: "EmailSettings",
                columns: new[] { "Id", "ApiKeyCipher", "FromAddress", "FromName", "InviteExpiryDays", "LastTestAt", "LastTestError", "LastTestOk", "MailgunDomain", "MailgunRegion", "PublicBaseUrl", "UpdatedAt", "UpdatedByUserId" },
                values: new object[] { 1, null, "", "Keepr", 7, null, null, null, null, null, "", new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)), null });
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            // Drop EmailSettings only. DataProtectionKeys is deliberately RETAINED: the key ring is
            // shared with the framework's auth-cookie and antiforgery protection, so dropping it would
            // fail cookie/token validation (signing every user out) and make any stored ApiKeyCipher
            // permanently undecryptable. Retiring the ring is a separate, explicitly-destructive
            // operation, never a side effect of rolling this feature back. Re-creating the table on a
            // re-apply is idempotent. See docs/feature-36-email-providers.md §8.
            migrationBuilder.DropTable(
                name: "EmailSettings",
                schema: "keepr");
        }
    }
}
